// Playground - noun: a place where people can play

import Foundation
//import SwiftMarshal

let rawCookieString = "BAh7C0kiFXVzZXJfY3JlZGVudGlhbHMGOgZFRkkiAYAwOGIyMjQyZWJmNDBjMzM5ZjQ3MzEzMDliMDg2OWY5YmU3MTM1MzE3NzZkZTZhOTNhMGMzMjZlZjQzNzczYjI1YzA0ODcyNmRmMjhlNTFlMmVkZmI3YTAyNTQ0MWNiZTYzNmI4NjJlMWRiY2VmYmQzYmQ5OWQ2YmY1MmY0ZDg4MwY7AFRJIhh1c2VyX2NyZWRlbnRpYWxzX2lkBjsARmkDXzUCSSIKZmxhc2gGOwBGbzolQWN0aW9uRGlzcGF0Y2g6OkZsYXNoOjpGbGFzaEhhc2gJOgpAdXNlZG86CFNldAY6CkBoYXNoewY6C25vdGljZVQ6DEBjbG9zZWRGOg1AZmxhc2hlc3sGOwpJIhxTdWNjZXNzZnVsbHkgbG9nZ2VkIGluLgY7AEY6CUBub3cwSSIPc2Vzc2lvbl9pZAY7AEZJIiU5YmVkNjNjMjZmNzI3YmNlZDVjMTViMDI0YTliZGM0MQY7AFRJIg5yZXR1cm5fdG8GOwBGIhkvdXNlcnMvdGhlYmx1ZXBvdGF0b0kiEF9jc3JmX3Rva2VuBjsARkkiMUg1VElkU0xHK1BlMXVwZzJmQ3Yybm5DTnVYQUloWHAyYS9OM0o3MVo5UEk9BjsARg%3D%3D--ade9d31d3baf7fc7a4126edc10808f1b8f8fa6c1"
let base64CookieData = rawCookieString.stringByRemovingPercentEncoding!.componentsSeparatedByString("--").first!
let cookieData = NSData(base64EncodedString: base64CookieData, options: NSDataBase64DecodingOptions.allZeros)!
let asciiString = NSString(data: cookieData, encoding: NSASCIIStringEncoding)!